version: '3.2'
volumes:
  postgres-data:
  redis-data:
  bundle-cache:
services:
  web:
    container_name: mce_rails
    image: mce/rails
    environment:
    - RAILS_ENV=development
    - EDITOR=vim
    - THOR_MERGE=vim
    - CONTACT_RECIPIENT=mail@gronows.com
    ports:
    - "3020:3000"
    depends_on:
    - db
    - redis
    - sidekiq
    volumes:
    - .:/app
    - bundle-cache:/bundle
    stdin_open: true
    tty: true
  sidekiq:
    build:
      context: .
      dockerfile: ./config/docker/dev/Dockerfile
    container_name: mce_sidekiq
    image: mce/rails
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - EDITOR=vim
      - CONTACT_RECIPIENT=mail@gronows.com
    ports:
      - "3120:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle-cache:/bundle
  db:
    container_name: mce_db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5484:5432"
  redis:
    container_name: mce_redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6382:6379"
