version: '3.7'
services:
  app:
    build:
      context: .docker
      dockerfile: Dockerfile
    entrypoint: /root/entrypoint.sh
    command: rails server -b 0.0.0.0
    image: mce/rails
    ports:
      - "3020:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails:/app/tmp/cache
      - bundle:/usr/local/bundle
      - .docker/.psqlrc:/root/.psqlrc:ro
      - .docker/.bashrc:/root/.bashrc:ro
      - .docker/.irbrc:/root/.irbrc
      - .docker/.gitconfig:/root/.gitconfig
      - .docker/entrypoint.sh:/root/entrypoint.sh
      - .docker/.pgpass:/root/.pgpass
    environment:
      APP_NAME: mce
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
      HISTFILE: /app/log/.bash_history
      PSQL_HISTFILE: /app/log/.psql_history
      EDITOR: vim
      CONTACT_RECIPIENT: mail@gronows.com
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker/.psqlrc:/root/.psqlrc:ro
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: password
    ports:
      - "5484:5432"

  redis:
    image: redis:alpine
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - .docker/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres:
    name: mce-postgres-data
  redis:
    name: mce-redis-data
  bundle:
    name: mce-bundle-cache
  rails:
    name: mce-rails-cache
