# Variables
substitutions:
  _APP_NAME: mce

steps:
# Get ssh key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=config/cloudbuild/github.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=cloud-build
  - --key=github-nick-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv config/cloudbuild/known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Use git clone.
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:online-ventures/$_APP_NAME.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Get access key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=config/cloudbuild/token.enc
  - --plaintext-file=/root/env
  - --location=global
  - --keyring=cloud-build
  - --key=digital-ocean-access-key
  volumes:
  - name: 'home'
    path: /root

# Set up kubectl
- name: 'gcr.io/web-online-ventures/curl'
  args: ['bash', 'config/cloudbuild/curl-config']
  volumes:
  - name: 'home'
    path: /root
  - name: '1001'
    path: /home/1001

# Update cluster pods
- name: 'bitnami/kubectl'
  args:
    - '--kubeconfig'
    - '/home/1001/kube'
    - 'set'
    - 'image'
    - 'deploy/$_APP_NAME'
    - 'rails=gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
    - '--namespace=default'
  volumes:
  - name: '1001'
    path: /home/1001

- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

- name: gcr.io/cloud-builders/docker
  dir: $_APP_NAME
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '-f', 'config/docker/app/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '.']

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

# Save this build as well according to commit sha
images:
- 'gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'

